### ISSUE TITLE
high load generated by unifiedbeat

### ISSUE THREAD

**Issue by slayer01** [cleesmith/unifiedbeat#3]
dear cleesmith,

first of all, thank you very much for your effort.

I installed unifiedbeat on my snort box, my snort version is 2.9.8.0 its running on centos 7.
Actually there are two unified log files:

```
-rw------- 1 snort snort 229K 10. Feb 10:35 snort.log.1455026918
-rw------- 1 snort snort  918 10. Feb 11:01 snort.log.1455097021
```

an top looks like this:

```
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                        
17321 root      20   0  145952  97140   5016 S 67,2  0,6   1:55.67 unifiedbeat                                                                                                                                    
17319 root      20   0  145952  97140   5016 R 66,2  0,6   1:43.55 unifiedbeat                                                                                                                                    
17317 root      20   0  145952  97140   5016 R 57,6  0,6   1:31.90 unifiedbeat                                                                                                                                    
17318 root      20   0  145952  97140   5016 S 15,6  0,6   1:44.70 unifiedbeat                                                                                                                                    
17320 root      20   0  145952  97140   5016 S  6,6  0,6   1:26.69 unifiedbeat                                                                                                                                    
17326 root      20   0  145952  97140   5016 S  6,6  0,6   1:45.11 unifiedbeat                                                                                                                                    
17332 root      20   0  145952  97140   5016 S  5,6  0,6   1:43.52 unifiedbeat                                                                                                                                    
17325 root      20   0  145952  97140   5016 S  4,6  0,6   1:51.60 unifiedbeat                                                                                                                                    
17328 root      20   0  145952  97140   5016 S  4,3  0,6   1:53.96 unifiedbeat                                                                                                                                    
17322 root      20   0  145952  97140   5016 S  4,0  0,6   1:25.09 unifiedbeat                                                                                                                                    
17323 root      20   0  145952  97140   5016 S  3,6  0,6   1:08.53 unifiedbeat                                                                                                                                    
17017 snort     20   0 1548952 767760   5824 S  2,6  4,7   2:26.04 snort                                                                                                                                          
17327 root      20   0  145952  97140   5016 S  2,6  0,6   1:55.36 unifiedbeat                                                                                                                                    
17331 root      20   0  145952  97140   5016 S  2,0  0,6   1:46.41 unifiedbeat                                                                                                                                    
17314 root      20   0  145952  97140   5016 S  1,3  0,6   1:31.76 unifiedbeat                                                                                                                                    
17315 root      20   0  145952  97140   5016 S  0,7  0,6   0:01.04 unifiedbeat  
```

so you see up to 15 unifiedbeat threads, first 5-10 use cpu about 20 - 70%. Is that normal behaviour?

Here is my unifiedbeat.yml

```
unifiedbeat:
  geoip2_path: "var/GeoIP/GeoLite2-City.mmdb"
  rules:
    gen_msg_map_path: "/etc/snort/gen-msg.map"
    paths:
      - "/etc/snort/rules/*.rules"
  sensor:
    -
      paths:
        - /var/log/snort/snort.log*

      fields:
        sensor_hostname: ultrasnort1
        sensor_interface: em2
        sensor_type: snort

      fields_under_root: true

      ignore_older: 24h

      scan_frequency: 20s

output:

  logstash:
    hosts: ["logstash.example.de:5044"]
    tls:
      certificate_authorities: ["/etc/pki/tls/certs/logstash.example.de.crt"]

shipper:
  name: nucy

logging:

  to_files: true

  files:
    path: /var/log/unifiedbeat

    name: unifiedbeat


    keepfiles: 3


  level: info
`
```
